### ISSUE TITLE
Using bitwise-equals operators with lua 5.1 causes cryptic error message

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#233]
Normally, when using bitwise ops with a lua 5.1 target, you get the error
```
Error: Bitwise operations is/are not supported for target Lua 5.1.
```

But, when using any of the bit-equals ops ('|=', '&=', etc...) the following error is reported:
```
node_modules\typescript\lib\typescript.js:4503
            throw e;
            ^

Error: Debug Failure. False expression: position cannot precede the beginning of the file
    at computeLineAndCharacterOfPosition (node_modules\typescript\lib\typescript.js:7112:22)
    at Object.getLineAndCharacterOfPosition (node_modules\typescript\lib\typescript.js:7121:16)
    at program.getSourceFiles.forEach.sourceFile (dist\Compiler.js:110:36)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (dist\Compiler.js:78:30)
    at compileFilesWithOptions (dist\Compiler.js:60:5)
    at Object.compile (dist\Compiler.js:19:9)
    at Object.<anonymous> (dist\index.js:5:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```
Which is much less helpful :)

**Comment by tomblind** [comment]
Interesting - I'm reworking that code in my PR to fix #221 so I'll have to factor that in. I'm curious why it only affected bitwise ops, though.

**Comment by Perryvw** [comment]
It happens because the binary expression node is added to the error message there. If the other temporary nodes that we create in the transpiler are never added to any error messages then this case should not occur.

**Comment by tomblind** [comment]
Ah - makes sense!
