### ISSUE TITLE
Error indexing tuple types

### ISSUE THREAD

**Issue by Trildar** [Perryvw/TypescriptToLua#6]
e.g. `let a: [number, string] = [1, "WASD"]; let b = a[0];` causes the following error:
```
c:\Users\User\Documents\TypescriptToLua\dist\Compiler.js:59
                    throw exception;
                    ^

TypeError: Cannot read property 'escapedName' of undefined
    at Function.TSHelper.isArrayType (c:\Users\User\Documents\TypescriptToLua\dist\TSHelper.js:35:65)
    at LuaTranspiler.transpileElementAccessExpression (c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:561:43)
    at LuaTranspiler.transpileExpression (c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:295:29)
    at LuaTranspiler.transpileVariableDeclaration (c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:584:34)
    at c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:574:29
    at Array.forEach (<anonymous>)
    at LuaTranspiler.transpileVariableStatement (c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:573:43)
    at LuaTranspiler.transpileNode (c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:75:43)
    at c:\Users\User\Documents\TypescriptToLua\dist\Transpiler.js:55:33
    at visitNodes (C:\Users\User\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:12699:30)
```

Tuple types apparently don't have a `symbol` property. Not sure what would be a good way to check for tuples.

**Comment by Perryvw** [comment]
Fixed in 24da494c5160a6dc87ebfd19ff927afacf55a0dc
