### ISSUE TITLE
Operator 'new' declaration error. Undefined behavior and Crash.

### ISSUE THREAD

**Issue by dasannikov** [Perryvw/TypescriptToLua#92]
I made a mistake and write in TS code file:
```
class A {}
export let a = new A

```
Transpiler always crashed with log:
```
E:\Defold\DasGame>tstl tests.ts
C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Compiler.js:57
                    throw exception;
                    ^

TypeError: Cannot read property 'forEach' of undefined
    at LuaTranspiler.transpileArguments (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:899:16)
    at LuaTranspiler.transpileNewExpression (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:756:27)
    at LuaTranspiler.transpileExpression (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:535:29)
    at LuaTranspiler.transpileVariableDeclaration (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:1006:34)
    at C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:996:29
    at Array.forEach (<anonymous>)
    at LuaTranspiler.transpileVariableStatement (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:995:43)
    at LuaTranspiler.transpileNode (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:157:26)
    at C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Transpiler.js:129:33
    at visitNodes (C:\Users\dasannikov\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:13999:30)
```
It have taken huge amount of time to find my mistake in TS code.
(No Transpiler notifications and Transpiler crash)

**Comment by lolleko** [comment]
Seems like we need to check if node.arguments exists before calling transpileArgs: https://github.com/Perryvw/TypescriptToLua/blob/master/src/Transpiler.ts#L836
