### ISSUE TITLE
TypeError: fs.copyFileSync is not a function

### ISSUE THREAD

**Issue by electricessence** [Perryvw/TypescriptToLua#98]
After npm install:

```
TypeError: fs.copyFileSync is not a function
    at compile (----\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Compiler.js:74:8)
    at execCommandLine (----\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Compiler.js:80:5)
    at Object.<anonymous> (----\AppData\Roaming\npm\node_modules\typescript-to-lua\dist\Compiler.js:83:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
```

**Comment by lolleko** [comment]
Your node version is probably outdated.

**Comment by electricessence** [comment]
K.  Will look into it.

**Comment by electricessence** [comment]
Confirmed.  Updated to 8.11.1 and it worked.  Very cool sir. :)
